### ISSUE TITLE
RequestsDependencyWarning

### ISSUE THREAD

**Issue by kgraefe** [joachimesque/Cast-Rewinder#10]
Your `requirements.txt` lists:
```
urllib3>=1.25.2
requests==2.21.0
```
but [`requests 2.21.0` requires `urllib3 >= 1.21.1, <= 1.24`](https://github.com/psf/requests/blob/v2.21.0/requests/__init__.py#L60)

Therefore `setup.py` issues a `RequestsDependencyWarning`:
```
/var/www/rewinder/venv/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
```

**Comment by joachimesque** [comment]
Ooh that's strange, I never got this warning (but the service has been running for some time without dependency updates). I'll try to make time this week to look at it!

**Comment by kgraefe** [comment]
It's not resticted to `setup.py` but also happens regularly on the Flask app and `feed_worker.py`

**Comment by kgraefe** [comment]
Also I had to `pip install 'Jinja2<3.0.0'` or I could not get migrations to run:
```
❯ FLASK_APP=castrewinder flask db init
Traceback (most recent call last):
  File "/var/www/rewinder/venv/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/var/www/rewinder/venv/lib/python3.7/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/var/www/rewinder/venv/lib/python3.7/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/var/www/rewinder/venv/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/var/www/rewinder/venv/lib/python3.7/site-packages/click/core.py", line 1061, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/var/www/rewinder/venv/lib/python3.7/site-packages/click/core.py", line 1100, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/var/www/rewinder/venv/lib/python3.7/site-packages/flask/cli.py", line 500, in get_command
    self._load_plugin_commands()
  File "/var/www/rewinder/venv/lib/python3.7/site-packages/flask/cli.py", line 496, in _load_plugin_commands
    self.add_command(ep.load(), ep.name)
  File "/var/www/rewinder/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2410, in load
    self.require(*args, **kwargs)
  File "/var/www/rewinder/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2433, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/var/www/rewinder/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (MarkupSafe 1.0 (/var/www/rewinder/venv/lib/python3.7/site-packages), Requirement.parse('MarkupSafe>=2.0'), {'Jinja2'})
```

TBH I don't know what migrations are in that context, but either downgrading Jinja2 or running `flask db init` (probably that) got me around `sqlite3.OperationalError: no such column: feed.etag` in `feed_worker.py` as well as the Flask app.

**Comment by kgraefe** [comment]
This is fixed with the recent dependency updates.
